---
- name: Install Apache on EC2 instances
  hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
